"""
Meeting Analysis Service for SynkAI.
Executes the LangGraph multi-agent workflow over meeting transcripts.
"""

from backend.agents.parser_agent import AGENT_NAME as PARSER_AGENT_NAME
from backend.graph.meeting_graph import LLM_AGENT_NAMES, create_meeting_graph, MeetingState
from backend.models.analysis import MeetingAnalysisResponse
from backend.utils.logger import get_logger

logger = get_logger(__name__)


class MeetingAnalysisService:
    """
    Service responsible for orchestrating the multi-agent meeting analysis.
    """

    def __init__(self):
        self.graph = create_meeting_graph()

    def analyze_transcript(self, transcript_text: str) -> MeetingAnalysisResponse:
        """
        Executes the LangGraph workflow to extract structured meeting intelligence.

        Agents run one at a time (see backend/graph/meeting_graph.py). Individual agent
        failures are reported on the response via `analysis_complete` / `agent_errors`;
        a total failure raises so the caller receives an error rather than an empty result.

        Args:
            transcript_text (str): Raw transcript text.

        Returns:
            MeetingAnalysisResponse: Combined structured meeting intelligence response.

        Raises:
            ValueError: If the transcript is empty.
            RuntimeError: If the workflow crashed, or if no agent produced any output.
        """
        logger.info("LangGraph workflow started.")

        if not transcript_text or not transcript_text.strip():
            logger.error("Empty transcript provided to MeetingAnalysisService.")
            raise ValueError("Transcript text cannot be empty.")

        # Initial state setup
        initial_state: MeetingState = {
            "transcript": transcript_text,
            "parsed_transcript": "",
            "summary_data": {},
            "action_items": [],
            "decisions": [],
            "deadlines": [],
            "risks": [],
            "agent_errors": [],
            "final_analysis": None
        }

        try:
            logger.info(f"Invoking LangGraph workflow sequentially over {len(transcript_text)} characters...")
            final_state = self.graph.invoke(initial_state)
            logger.info("LangGraph workflow execution completed.")
        except Exception as exc:
            logger.error(f"Error during LangGraph meeting analysis execution: {exc}", exc_info=True)
            raise RuntimeError(f"Multi-agent analysis workflow execution failed: {str(exc)}") from exc

        final_response = final_state.get("final_analysis")
        if not final_response:
            raise RuntimeError("Workflow completed but final_analysis is missing in state.")

        self._raise_if_total_failure(final_state.get("agent_errors") or [])

        if final_response.analysis_complete:
            logger.info("Final analysis generated by all agents.")
        else:
            failed = ", ".join(err.agent for err in final_response.agent_errors)
            logger.error(f"Final analysis is PARTIAL. Failed agents: {failed}.")

        return final_response

    @staticmethod
    def _raise_if_total_failure(agent_errors: list) -> None:
        """
        Raises when the workflow produced nothing usable, so failures are never returned
        to the client disguised as a successful-but-empty analysis.

        Args:
            agent_errors (list): Recorded {'agent', 'error'} dicts from the workflow state.

        Raises:
            RuntimeError: If the Parser Agent failed, or if every LLM agent failed.
        """
        failed_agents = {err.get("agent") for err in agent_errors}

        if PARSER_AGENT_NAME in failed_agents:
            reason = next(err["error"] for err in agent_errors if err.get("agent") == PARSER_AGENT_NAME)
            raise RuntimeError(f"Transcript could not be parsed, analysis aborted: {reason}")

        if failed_agents and set(LLM_AGENT_NAMES).issubset(failed_agents):
            reasons = "; ".join(f"{err['agent']}: {err['error']}" for err in agent_errors)
            raise RuntimeError(f"Every analysis agent failed, no meeting intelligence produced. {reasons}")
