"""
Pydantic schemas for meeting summarization request and response.
"""

from typing import List, Optional
from pydantic import BaseModel, Field


class SummaryRequest(BaseModel):
    """
    Request model for meeting summarization endpoint.
    Provide either an uploaded filename or direct transcript_text.
    """
    filename: Optional[str] = Field(default=None, description="Filename of previously uploaded transcript in uploads/")
    transcript_text: Optional[str] = Field(default=None, description="Direct raw meeting transcript text")


class SummaryResponse(BaseModel):
    """
    Structured summary response generated by LLM.
    """
    executive_summary: str = Field(..., description="High-level executive summary of the meeting")
    key_discussion_points: List[str] = Field(..., description="List of primary topics and discussion points")
    meeting_outcome: str = Field(..., description="Key decisions, conclusions, and overall meeting outcome")
    model_used: str = Field(..., description="Ollama LLM model name used for summarization")
    filename: Optional[str] = Field(default=None, description="Associated file name if applicable")
